### ISSUE TITLE
Release version and bug fix handling 

### ISSUE THREAD

**Issue by veglar** [QlikDeploymentFramework/Qlik-Deployment-Framework#15]
I find that there are some confusion regarding bug fixes and versions. 

QDF version 1.7.2 has been the last release for a while, but there has been made 7 commits to the master since May 24th, some of them are very important bug fixes for Qlik Sense November 2018. I see troubled users that could have been helped it they grabbed the latest commit instead of the released version of the QDF. You have to know where to look to see the that there is a difference between the two.

I don't have a perfect solution for the problem, but I have two suggestions.

1. By visiting the the GitHub-page the [Qlik-Deployment-Framework/README.md](https://github.com/QlikDeploymentFramework/Qlik-Deployment-Framework/blob/master/README.md) I would be helped with an indication to the version number that this is not the released version eg
`QDF version 1.7.2 (adjusted).`

2. More frequent releases, adding a SR to minor bug fixes like 1.7.2 SR1 and 1.7.2 SR2 **or** just increase the version number per committed bug fix. 1.7.3 and 1.7.4.

Cheers
Vegar

**Comment by edwardhallgren** [comment]
Any response @QlikDeploymentFramework ?

**Comment by QlikDeploymentFramework** [comment]
The current version should have the correct workarounds for Nov 2018, please come back if that's not the case? regards Magnus

**Comment by QlikDeploymentFramework** [comment]
1.7.3 contains bugfixes for November2018

**Comment by ArishDelon** [comment]
1.7.3 is not support on Windows Server 2016. Any idea when will this be supported?

See follow link:

**Comment by ArishDelon** [comment]
QDF 1.7.3 does not run on windows server 2016.

Global variables does not work in QDF. See following link below with test evidence and error message.

[https://community.qlik.com/t5/Qlik-Deployment-Framework/Qlik-Deployment-Framework-1-7-3/gpm-p/1568747#M2124](url)

**Comment by veglar** [comment]
@ArishDelon is it the framework as a whole that you have issues with it or just the QlikView variable editor as mentioned in the link you provided?

**Comment by ArishDelon** [comment]
Hello Veglar,

Good Question.

When i launch QDF 1.7.3

The frame work editor reads as 1.6.0

1. The container map editor does not work here. if you launch it you will get an error: Execution of script failed. Reload old data. "Variable editor could not find deployment framework core. The application will not work".
![Framework](https://user-images.githubusercontent.com/49488763/58508061-225f6a00-8161-11e9-9831-31ae748063f5.JPG)

2. When you launch variable editor,  "Variable editor could not find deployment framework core. The application will not work." 
You are not able to select drop down menu "Variable files" or "Select Container"
![Variable Editor](https://user-images.githubusercontent.com/49488763/58508530-3bb4e600-8162-11e9-8807-3d4f98c0ea7b.JPG)

3. If you select Settings and template, You are not able to make any changes because it look for a file in the wrong location.
![SettingsandTemplate](https://user-images.githubusercontent.com/49488763/58508771-d1507580-8162-11e9-8731-dbf851eacde4.JPG)

All these test were done on Windows 2016 environment running VM Ware.
Hope i was able to provide valuable information
